/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controllers.KeHoachBaoTriController;
import Interfaces.ErrorDatabase;
import Interfaces.ErrorNormal;
import Interfaces.NotifyNormal;
import Models.KeHoachBaoTri;
import Models.NghiepVuBaoTriTaiSan;
import Models.NhiemVuBaoTri;
import Models.PhongMay;
import Models.PhongMayDAO;
import Models.TaiSan;
import Models.TaiSanBaoTri;
import Models.TaiSanDAO;
import Models.TaiSanPhongMay;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author thinh
 */
public class Add_UpdateTaiSanBaoTri extends javax.swing.JFrame {

    private KeHoachBaoTriController keHoachBaoTriController;
    private TaiSanBaoTri taiSanBaoTri;
    private NhiemVuBaoTri nhiemVuBaoTri;
    private boolean isAddKeHoachBaoTri;
    private boolean isAddTaiSanBaoTri;
    private HashMap<String, String> phongMayHashMap;
    private HashMap<String, String> taiSanHashMap;
    
    
    public Add_UpdateTaiSanBaoTri() {
        initComponents();
    }
    
    public Add_UpdateTaiSanBaoTri(KeHoachBaoTriController keHoachBaoTriController, TaiSanBaoTri taiSanBaoTri, boolean isAddKeHoachBaoTri) {
        initComponents();
        this.keHoachBaoTriController = keHoachBaoTriController;
        this.taiSanBaoTri = taiSanBaoTri;
        this.isAddKeHoachBaoTri = isAddKeHoachBaoTri;
        this.isAddTaiSanBaoTri = false;
        
        hienThiUIforUpdate();
    }
    
    public Add_UpdateTaiSanBaoTri(KeHoachBaoTriController keHoachBaoTriController, NhiemVuBaoTri nhiemVuBaoTri, boolean isAddKeHoachBaoTri) {
        initComponents();
        this.keHoachBaoTriController = keHoachBaoTriController;
        this.nhiemVuBaoTri = nhiemVuBaoTri;
        this.isAddKeHoachBaoTri = isAddKeHoachBaoTri;
        this.isAddTaiSanBaoTri = true;
        
        hienThiUIforAdd();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TF_soLuong = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TF_yeuCauBaoTri = new javax.swing.JTextField();
        Btn_add = new javax.swing.JButton();
        Btn_Delete = new javax.swing.JButton();
        Btn_update = new javax.swing.JButton();
        Btn_cancel = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        CB_PhongMay = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        CB_TaiSan = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tài sản bảo trì");

        jLabel2.setText("Số lượng:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TF_soLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TF_soLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLabel5.setText("Yêu cầu bảo trì:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(TF_yeuCauBaoTri, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TF_yeuCauBaoTri, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addContainerGap())
        );

        Btn_add.setText("Thêm");
        Btn_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_addMouseClicked(evt);
            }
        });

        Btn_Delete.setText("Xóa");
        Btn_Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_DeleteMouseClicked(evt);
            }
        });

        Btn_update.setText("Cập nhật");
        Btn_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_updateMouseClicked(evt);
            }
        });

        Btn_cancel.setText("Hủy");
        Btn_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_cancelMouseClicked(evt);
            }
        });

        jLabel6.setText("Phòng máy:");

        CB_PhongMay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(CB_PhongMay, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(CB_PhongMay))
                .addContainerGap())
        );

        jLabel7.setText("Tài sản:");

        CB_TaiSan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(CB_TaiSan, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(CB_TaiSan))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(356, 356, 356)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addGap(438, 438, 438))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(Btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(Btn_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(Btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_cancelMouseClicked
        this.dispose();
    }//GEN-LAST:event_Btn_cancelMouseClicked

    private void Btn_updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_updateMouseClicked
        if(isAddKeHoachBaoTri) {
        
        }else {
            try {
                keHoachBaoTriController.updateTaiSanBaotri(getTaiSanBaoTribyForm());
                this.dispose();
                keHoachBaoTriController.getChiTietKeHoachBaoTriView().hienThiNhiemVuBaoTriByUpDateKeHoachBaoTri();
            } catch (SQLException ex) {
                ErrorDatabase errorDatabase = new ErrorDatabase();
                errorDatabase.HienThiThongBaoLoi(ex.getMessage());
            } catch (NumberFormatException ex) {
                ErrorNormal errorNormal = new ErrorNormal(ex.getMessage());
                errorNormal.HienThiThongBaoLoi();
            }
        }
    }//GEN-LAST:event_Btn_updateMouseClicked

    private void Btn_DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_DeleteMouseClicked
        if(isAddKeHoachBaoTri) {
        
        }else {
            keHoachBaoTriController.deleteTaiSanBaoTri(taiSanBaoTri);
            keHoachBaoTriController.getChiTietKeHoachBaoTriView().hienThiNhiemVuBaoTriByUpDateKeHoachBaoTri();
        }
    }//GEN-LAST:event_Btn_DeleteMouseClicked

    private void Btn_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_addMouseClicked
        if(isAddKeHoachBaoTri) {
            
        } else {
            try {
                keHoachBaoTriController.addTaiSanBaoTri(getTaiSanBaoTriToAddTaiSanBaoTribyForm());
                this.dispose();
                keHoachBaoTriController.getChiTietKeHoachBaoTriView().hienThiNhiemVuBaoTriByUpDateKeHoachBaoTri();
            } catch (SQLException ex) {
                ErrorDatabase errorDatabase = new ErrorDatabase();
                errorDatabase.HienThiThongBaoLoi(ex.getMessage());
            } catch (NumberFormatException ex) {
                ErrorNormal errorNormal = new ErrorNormal(ex.getMessage());
                errorNormal.HienThiThongBaoLoi();
            }
        }
    }//GEN-LAST:event_Btn_addMouseClicked

    private TaiSanBaoTri getTaiSanBaoTriToAddTaiSanBaoTribyForm() throws SQLException, NumberFormatException {
        TaiSanBaoTri taiSanBaoTribyform = new TaiSanBaoTri();
        
        taiSanBaoTribyform.setiD(keHoachBaoTriController.randomIDWith6Char());
        taiSanBaoTribyform.setiDNhiemVuBaoTri(nhiemVuBaoTri.getiD());
        taiSanBaoTribyform.setiDTaiSanPhongMay(getTaiSanPhongMaybyForm().getiD());
        taiSanBaoTribyform.setYeuCauBaoTri(TF_yeuCauBaoTri.getText());
        taiSanBaoTribyform.setSoLuong(Integer.parseInt(TF_soLuong.getText()));
        
        return taiSanBaoTribyform;
    }
    
    private TaiSanBaoTri getTaiSanBaoTribyForm() throws SQLException, NumberFormatException {
        TaiSanBaoTri taiSanBaoTribyform = new TaiSanBaoTri();
        taiSanBaoTribyform.setiD(taiSanBaoTri.getiD());
        taiSanBaoTribyform.setiDNhiemVuBaoTri(taiSanBaoTri.getiDNhiemVuBaoTri());
        taiSanBaoTribyform.setiDTaiSanPhongMay(getTaiSanPhongMaybyForm().getiD());
        taiSanBaoTribyform.setYeuCauBaoTri(TF_yeuCauBaoTri.getText());
        taiSanBaoTribyform.setSoLuong(Integer.parseInt(TF_soLuong.getText()));
        
        return taiSanBaoTribyform;
    }
    
    private TaiSanPhongMay getTaiSanPhongMaybyForm() throws SQLException {
        String tenTaiSan = (String) CB_TaiSan.getSelectedItem();
        String iDTaiSan = "";
        
        for (Map.Entry<String, String> entry : taiSanHashMap.entrySet()) {
            if (entry.getValue().equals(tenTaiSan)) {
                iDTaiSan = entry.getKey();
                break;
            }
        }
        
        String tenPhongMay = (String) CB_PhongMay.getSelectedItem();
        String iDPhongMay = "";
        
        for (Map.Entry<String, String> entry : phongMayHashMap.entrySet()) {
            if (entry.getValue().equals(tenPhongMay)) {
                iDPhongMay = entry.getKey();
                break;
            }
        }
        
        return getTaiSanPhongMaybyiDTaiSan_iDPhongMay(iDTaiSan, iDPhongMay);
    }
    
    // Thịnh thêm get bằng iDTaiSan và iDPhongMay
    public TaiSanPhongMay getTaiSanPhongMaybyiDTaiSan_iDPhongMay(String iDtaiSan, String iDPhongMay) throws SQLException {
        TaiSanPhongMay taiSanPhongMay = new TaiSanPhongMay();
        Connection conn = Database.DatabaseHelper.getDBConnection();
        Statement sttm = conn.createStatement();
        String query = "select * from TaiSanPhongMay where iDTaiSan =" + "'" + iDtaiSan + "'" + "and iDPhongMay = " + "'" + iDPhongMay +"'";
        ResultSet result = sttm.executeQuery(query);
        
        while(result.next()) {
            taiSanPhongMay.setiD(result.getString(1));
            taiSanPhongMay.setiDTaiSan(result.getString(2));
            taiSanPhongMay.setiDPhongMay(result.getString(3));
            taiSanPhongMay.setSoLuong(result.getInt(4));
        }
        
        return taiSanPhongMay;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_UpdateTaiSanBaoTri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_UpdateTaiSanBaoTri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_UpdateTaiSanBaoTri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_UpdateTaiSanBaoTri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_UpdateTaiSanBaoTri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Delete;
    private javax.swing.JButton Btn_add;
    private javax.swing.JButton Btn_cancel;
    private javax.swing.JButton Btn_update;
    private javax.swing.JComboBox<String> CB_PhongMay;
    private javax.swing.JComboBox<String> CB_TaiSan;
    private javax.swing.JTextField TF_soLuong;
    private javax.swing.JTextField TF_yeuCauBaoTri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables

    private void hienThiUIforUpdate() {
        Btn_add.setVisible(false);
        TF_soLuong.setText(taiSanBaoTri.getSoLuong() + "");
        TF_yeuCauBaoTri.setText(taiSanBaoTri.getYeuCauBaoTri());
        
        hienThiComboBoxForPhongMay();
        hienThiComboBoxForTaiSan();
    }

    private void hienThiUIforAdd() {
        Btn_update.setVisible(false);
        Btn_Delete.setVisible(false);
        hienThiComboBoxForPhongMay();
        hienThiComboBoxForTaiSan();
    }
    
    private void hienThiComboBoxForPhongMay() {
        PhongMayDAO phongMayDAO = new PhongMayDAO();
        ArrayList<PhongMay> phongMaysList = (ArrayList < PhongMay >)phongMayDAO.getAll();
        
        phongMayHashMap = new HashMap<>();
        
        phongMaysList.forEach(phongMay -> {
            phongMayHashMap.put(phongMay.getMaPhong(), phongMay.getTenPhong());
        });
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(phongMayHashMap.values().toArray(new String[0]));
        CB_PhongMay.setModel(model);
    }
    
    private void hienThiComboBoxForTaiSan() {        
        TaiSanDAO taiSanDAO = new TaiSanDAO();
        ArrayList<TaiSan> taiSansList = (ArrayList<TaiSan>)taiSanDAO.getAll();
        
        taiSanHashMap = new HashMap<>();
        
        taiSansList.forEach(taiSan -> {
            taiSanHashMap.put(taiSan.getMaTaiSan(), taiSan.getTenTaiSan());
        });
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(taiSanHashMap.values().toArray(new String[0]));
        CB_TaiSan.setModel(model);
    }
    
    
}
