/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Models.TaiSanPhongMay;
import Models.TaiSanPhongMayDAO;
import Models.BaoCao;
import Models.BaoCaoDAO;
import Models.TaiSan;
import Models.TaiSanDAO;
import static java.lang.Integer.parseInt;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author IT SUP
 */
public class JFBaoCaoKiemKe extends javax.swing.JFrame {

    /**
     * Creates new form JFBaoCaoKiemKe
     */
    public JFBaoCaoKiemKe() {
        initComponents();
        fillTableBC();
    }

    public void fillTableBC() {
        DefaultTableModel bcModel = (DefaultTableModel) jTableBaoCao.getModel();
        bcModel.setRowCount(0);
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        for (BaoCao bc : bcDAO.getAll()) {
            Object dataRow[] = new Object[6];
            dataRow[0] = bc.getNgayThucHien().format(formatter);
            dataRow[1] = bc.getPhong();
            dataRow[2] = bc.getNguoiKiemKe();
            dataRow[3] = bc.getTenTaiSan();
            dataRow[4] = bc.getSoLuong();
            dataRow[5] = bc.getGhiChu();
            bcModel.addRow(dataRow);
        }
    }
    
    public void resetForm(){
        jTextFieldNgayThucHien.setText("");
        jTextFieldPhong.setText("");
        jTextFieldNguoiKiemKe.setText("");
        jTextFieldTenTaiSan.setText("");
        jTextFieldSoLuong.setText("");
        jTextFieldGhiChu.setText("");
    }
    
    BaoCaoDAO bcDAO = new BaoCaoDAO();
    
    public BaoCao getModel(){
        BaoCao bc = new BaoCao();
        String ngayThucHienString = jTextFieldNgayThucHien.getText().trim();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate ngayThucHien = LocalDate.parse(ngayThucHienString, formatter);
        bc.setNgayThucHien(ngayThucHien);
        bc.setPhong(jTextFieldPhong.getText().trim());
        bc.setNguoiKiemKe(jTextFieldNguoiKiemKe.getText().trim());        
        bc.setTenTaiSan(jTextFieldTenTaiSan.getText().trim());
        bc.setSoLuong(parseInt(jTextFieldSoLuong.getText().trim()));
        bc.setGhiChu(jTextFieldGhiChu.getText().trim());
        return bc;
    }
    
    public void setModel(BaoCao bc){
        LocalDate ngayThucHien = bc.getNgayThucHien();
        String ngayThucHienString = ngayThucHien.toString(); 
        jTextFieldNgayThucHien.setText(ngayThucHienString);
        jTextFieldPhong.setText(bc.getPhong());
        jTextFieldNguoiKiemKe.setText(bc.getNguoiKiemKe());
        jTextFieldTenTaiSan.setText(bc.getTenTaiSan());
        jTextFieldSoLuong.setText(Integer.toString(bc.getSoLuong()));
        jTextFieldGhiChu.setText(bc.getGhiChu());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNgayThucHien = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNguoiKiemKe = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldSoLuong = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTenTaiSan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBaoCao = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableTaiSanPhong = new javax.swing.JTable();
        jButtonTim = new javax.swing.JButton();
        jButtonLamMoiBC = new javax.swing.JButton();
        jButtonSuaBC = new javax.swing.JButton();
        jButtonThem = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldPhong = new javax.swing.JTextField();
        jButtonXemTaiSan = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldGhiChu = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("BÁO CÁO");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        jLabel2.setText("Ngày thực hiện");

        jTextFieldNgayThucHien.setText(" ");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        jLabel3.setText("Người kiểm kê");

        jTextFieldNguoiKiemKe.setText(" ");

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        jLabel4.setText("Tên tài sản");

        jTextFieldSoLuong.setText(" ");

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        jLabel5.setText("Số lượng");

        jTextFieldTenTaiSan.setText(" ");

        jTableBaoCao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ngày thực hiện", "Phòng", "Người kiểm kê", "Tên tài sản", "Số lượng", "Ghi chú"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableBaoCao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBaoCaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableBaoCao);

        jTableTaiSanPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã tài sản", "Tên tài sản", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableTaiSanPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTaiSanPhongMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableTaiSanPhong);

        jButtonTim.setText("Tìm");
        jButtonTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimActionPerformed(evt);
            }
        });

        jButtonLamMoiBC.setText("Làm mới");
        jButtonLamMoiBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLamMoiBCActionPerformed(evt);
            }
        });

        jButtonSuaBC.setText("Sửa");
        jButtonSuaBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaBCActionPerformed(evt);
            }
        });

        jButtonThem.setText("Thêm");
        jButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        jLabel8.setText("Phòng");

        jTextFieldPhong.setText(" ");

        jButtonXemTaiSan.setText("Xem tài sản");
        jButtonXemTaiSan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXemTaiSanActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        jLabel7.setText("Ghi chú");

        jTextFieldGhiChu.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTenTaiSan, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNguoiKiemKe)
                                    .addComponent(jTextFieldNgayThucHien)
                                    .addComponent(jTextFieldGhiChu)
                                    .addComponent(jTextFieldSoLuong))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonSuaBC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonLamMoiBC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(51, 51, 51)
                                .addComponent(jLabel8)
                                .addGap(51, 51, 51)
                                .addComponent(jTextFieldPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                .addGap(28, 28, 28)
                                .addComponent(jButtonXemTaiSan)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNgayThucHien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTim)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonXemTaiSan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNguoiKiemKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonThem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldTenTaiSan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSuaBC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLamMoiBC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimActionPerformed
        // TODO add your handling code here:
        if(jTextFieldNgayThucHien.getText().isEmpty() && jTextFieldPhong.getText().isEmpty() && jTextFieldTenTaiSan.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập kiểu tìm kiếm!");
        } else {
            List<BaoCao> lbc = new ArrayList<>();
            String ngayThucHienString = jTextFieldNgayThucHien.getText().trim();
            if(!ngayThucHienString.isEmpty())
            {
                lbc = bcDAO.findBCByNTH(LocalDate.parse(jTextFieldNgayThucHien.getText()));
                if(lbc != null)
                    fillTableBaoCao(lbc);
                else
                    JOptionPane.showMessageDialog(this, "Không tìm thấy!");
            }
            if(!jTextFieldPhong.getText().isEmpty())
            {
                lbc = bcDAO.findBCByP(jTextFieldPhong.getText());
                if(lbc != null)
                    fillTableBaoCao(lbc);
                else
                    JOptionPane.showMessageDialog(this, "Không tìm thấy!");
            }
            if(!jTextFieldTenTaiSan.getText().isEmpty())
            {
                lbc = bcDAO.findBCByTTS(jTextFieldTenTaiSan.getText());
                if(lbc != null)
                    fillTableBaoCao(lbc);
                else
                    JOptionPane.showMessageDialog(this, "Không tìm thấy!");
            }
        }
    }//GEN-LAST:event_jButtonTimActionPerformed

    public void fillTableBaoCao(List<BaoCao> lbc){
        DefaultTableModel bckkModel = (DefaultTableModel) jTableBaoCao.getModel();
        bckkModel.setRowCount(0);     
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        for(int i = 0; i < lbc.size(); i++){
            Object dataRow[] = new Object[6];
            BaoCao bc = lbc.get(i);
            dataRow[0] = bc.getNgayThucHien().format(formatter);
            dataRow[1] = bc.getPhong();
            dataRow[2] = bc.getNguoiKiemKe();   
            dataRow[3] = bc.getTenTaiSan();
            dataRow[4] = bc.getSoLuong();
            dataRow[5] = bc.getGhiChu();
            bckkModel.addRow(dataRow); 
        }
    }
    
    private void jButtonLamMoiBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLamMoiBCActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_jButtonLamMoiBCActionPerformed

    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed
        // TODO add your handling code here:
        BaoCao bc = getModel();
        if(bcDAO.add(bc) > 0)
        {
            JOptionPane.showMessageDialog(this, "Thêm thành công!");
            fillTableBC();
        }                 
    }//GEN-LAST:event_jButtonThemActionPerformed

    private void jButtonSuaBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaBCActionPerformed
        // TODO add your handling code here:
        BaoCao bc = getModel();
        if(bcDAO.update(bc) > 0){
            JOptionPane.showMessageDialog(this, "Sửa thành công!");
            fillTableBC();        
        }           
    }//GEN-LAST:event_jButtonSuaBCActionPerformed

    private void jButtonXemTaiSanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXemTaiSanActionPerformed
        // TODO add your handling code here:
        if(jTextFieldPhong.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập phòng!");
        } else {
            List<TaiSanPhongMay> ls = new ArrayList<>();
            ls = tspmDAO.getTaiSanPhongMayByiDPhongMay(jTextFieldPhong.getText());
            if(ls != null)
                fillTableTaiSanPhongMay(ls);
            else
                JOptionPane.showMessageDialog(this, "Không tìm thấy phòng!");
        }
    }//GEN-LAST:event_jButtonXemTaiSanActionPerformed

    TaiSanPhongMayDAO tspmDAO = new TaiSanPhongMayDAO();
    TaiSanDAO tsDAO = new TaiSanDAO();
    
    public void fillTableTaiSanPhongMay(List<TaiSanPhongMay> ls){
        DefaultTableModel tspmModel = (DefaultTableModel) jTableTaiSanPhong.getModel();
        tspmModel.setRowCount(0);     
        for(int i = 0; i < ls.size(); i++){
            Object dataRow[] = new Object[3];
            TaiSanPhongMay tspm = ls.get(i);
            TaiSan ts = tsDAO.findTSByID(tspm.getiDTaiSan());
            dataRow[0] = tspm.getiDTaiSan();
            dataRow[1] = ts.getTenTaiSan();
            dataRow[2] = tspm.getSoLuong();  
            tspmModel.addRow(dataRow);
        }    
    }
    
    //String maTaiSanPhongClick = "-1";
    private void jTableTaiSanPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTaiSanPhongMouseClicked
        // TODO add your handling code here:
//        int position = jTableTaiSanPhong.rowAtPoint(evt.getPoint());
//        maTaiSanPhongClick = jTableTaiSanPhong.getValueAt(position, 0).toString();
//        TaiSanPhongMay tspm = tspmDAO.getTaiSanPhongMayByiDPhongMay(maTaiSanPhongClick);
//        if(tspm != null)
//            setModelTSPM(tspm);
    }//GEN-LAST:event_jTableTaiSanPhongMouseClicked
    
    String ngayThucHienString = "1111-11-11";
    LocalDate ngayThucHien = LocalDate.parse(ngayThucHienString);
    String phong = "-1";
    String nguoiKiemKe = "-1";
    private void jTableBaoCaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBaoCaoMouseClicked
        // TODO add your handling code here:    
        jTextFieldNgayThucHien.setEnabled(false);
        jTextFieldNguoiKiemKe.setEnabled(false);
        int position = jTableBaoCao.rowAtPoint(evt.getPoint());
        ngayThucHien = LocalDate.parse(jTableBaoCao.getValueAt(position, 0).toString());
        phong = jTableBaoCao.getValueAt(position, 1).toString();
        nguoiKiemKe = jTableBaoCao.getValueAt(position, 2).toString();
        BaoCao bc = bcDAO.findBCByNgayPhongNguoi(ngayThucHien,phong,nguoiKiemKe);
        if(bc != null)
            setModel(bc);
    }//GEN-LAST:event_jTableBaoCaoMouseClicked
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFBaoCaoKiemKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFBaoCaoKiemKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFBaoCaoKiemKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFBaoCaoKiemKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JFBaoCaoKiemKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLamMoiBC;
    private javax.swing.JButton jButtonSuaBC;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonTim;
    private javax.swing.JButton jButtonXemTaiSan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableBaoCao;
    private javax.swing.JTable jTableTaiSanPhong;
    private javax.swing.JTextField jTextFieldGhiChu;
    private javax.swing.JTextField jTextFieldNgayThucHien;
    private javax.swing.JTextField jTextFieldNguoiKiemKe;
    private javax.swing.JTextField jTextFieldPhong;
    private javax.swing.JTextField jTextFieldSoLuong;
    private javax.swing.JTextField jTextFieldTenTaiSan;
    // End of variables declaration//GEN-END:variables
}
