/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Models.TaiSanDAO;
import Models.TaiSan;
import java.time.LocalDate;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import Models.KeHoachThayDoiTaiSan;
import Models.NhiemVuThayDoiTaiSan;
import Models.TaiSanThayDoi;

/**
 *
 * @author IT SUP
 */
public class JFChiTietKeHoach extends javax.swing.JFrame {

    /**
     * Creates new form JFChiTietKeHoach
     */
    public JFChiTietKeHoach() {
        initComponents();
    }

    public void setModel2(KeHoachThayDoiTaiSan khtdts){
        jTextFieldMaKeHoach.setEnabled(false);
        jTextFieldThoiGianBatDau.setEnabled(false);
        jTextFieldThoiGianKetThuc.setEnabled(false);
                
        jTextFieldMaKeHoach.setText(khtdts.getMaKeHoach());
        
        LocalDate thoiGianBatDau = khtdts.getThoiGianBatDau();
        String thoiGianBatDauString = thoiGianBatDau.toString(); 
        jTextFieldThoiGianBatDau.setText(thoiGianBatDauString);
        
        LocalDate thoiGianKetThuc = khtdts.getThoiGianKetThuc();
        String thoiGianKetThucString = thoiGianKetThuc.toString(); 
        jTextFieldThoiGianKetThuc.setText(thoiGianKetThucString);
    }
    TaiSanDAO tsDAO = new TaiSanDAO();
    public void fillTableTaiSanThayDoi(List<TaiSanThayDoi> ls){
        DefaultTableModel tstdModel = (DefaultTableModel) jTableTaiSan.getModel();
        tstdModel.setRowCount(0);     
        for(int i = 0; i < ls.size(); i++){
            Object dataRow[] = new Object[5];
            TaiSanThayDoi tstd = ls.get(i);
            TaiSan ts = tsDAO.findTSByID(tstd.getMaTaiSan());
            dataRow[0] = tstd.getMaTaiSan();
            dataRow[1] = tstd.getiDTaiSanPhongMay();
            dataRow[2] = ts.getTenTaiSan();
            dataRow[3] = tstd.getSoLuong(); 
            dataRow[4] = tstd.getTrangThai();
            tstdModel.addRow(dataRow);
        }    
    }
    public void fillTableNhiemVu(List<NhiemVuThayDoiTaiSan> ls){
        DefaultTableModel nvtdtsModel = (DefaultTableModel) jTableNhiemVu.getModel();
        nvtdtsModel.setRowCount(0);     
        for(int i = 0; i < ls.size(); i++){
            Object dataRow[] = new Object[3];
            NhiemVuThayDoiTaiSan nvtdts = ls.get(i);           
            dataRow[0] = nvtdts.getiD();
            dataRow[1] = nvtdts.getTenNhiemVu();
            dataRow[2] = nvtdts.getChiTietNhiemVu();           
            nvtdtsModel.addRow(dataRow);
        }    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldMaKeHoach = new javax.swing.JTextField();
        jTextFieldThoiGianBatDau = new javax.swing.JTextField();
        jTextFieldThoiGianKetThuc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNhiemVu = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTaiSan = new javax.swing.JTable();
        jButtonThoat = new javax.swing.JButton();
        jButtonHoanThanh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("CHI TIẾT KẾ HOẠCH");

        jLabel2.setText("Mã kế hoạch");

        jLabel3.setText("Thời gian bắt đầu");

        jLabel4.setText("Thời gian kết thúc");

        jTableNhiemVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên nhiệm vụ", "Chi tiết nhiệm vụ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableNhiemVu);

        jTableTaiSan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã tài sản", "ID tài sản phòng máy", "Tên tài sản", "Số lượng", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableTaiSan);

        jButtonThoat.setText("Thoát");
        jButtonThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThoatActionPerformed(evt);
            }
        });

        jButtonHoanThanh.setText("Hoàn thành");
        jButtonHoanThanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHoanThanhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldMaKeHoach)
                                    .addComponent(jTextFieldThoiGianBatDau)
                                    .addComponent(jTextFieldThoiGianKetThuc)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonThoat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonHoanThanh)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(427, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(427, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldMaKeHoach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldThoiGianBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldThoiGianKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonThoat)
                    .addComponent(jButtonHoanThanh))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThoatActionPerformed
        // TODO add your handling code here:
        JFKeHoachThayDoiTaiSan jfkhtdts = new JFKeHoachThayDoiTaiSan();
        jfkhtdts.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonThoatActionPerformed

    private void jButtonHoanThanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHoanThanhActionPerformed
        // TODO add your handling code here:
        JFDanhGia jfdg = new JFDanhGia();
        jfdg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonHoanThanhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFChiTietKeHoach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFChiTietKeHoach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFChiTietKeHoach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFChiTietKeHoach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFChiTietKeHoach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHoanThanh;
    private javax.swing.JButton jButtonThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableNhiemVu;
    private javax.swing.JTable jTableTaiSan;
    private javax.swing.JTextField jTextFieldMaKeHoach;
    private javax.swing.JTextField jTextFieldThoiGianBatDau;
    private javax.swing.JTextField jTextFieldThoiGianKetThuc;
    // End of variables declaration//GEN-END:variables
}
