/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Models.NhiemVuThayDoiTaiSan;
import Models.NhiemVuThayDoiTaiSanDAO;

/**
 *
 * @author IT SUP
 */
public class JFNhiemVuThayDoiTaiSan extends javax.swing.JFrame {

    /**
     * Creates new form NhiemVuThayDoiTaiSan
     */
    public JFNhiemVuThayDoiTaiSan() {
        initComponents();
        fillTable();
    }

    public void fillTable(){
        DefaultTableModel nvtdtsModel = (DefaultTableModel) jTableNhiemVuThayDoiTaiSan.getModel();
        nvtdtsModel.setRowCount(0);
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        for(NhiemVuThayDoiTaiSan nvtdts : nvtdtsDAO.getAll()){
            Object dataRow[] = new Object[5];
            dataRow[0] = nvtdts.getiD();
            dataRow[1] = nvtdts.getiDKeHoachThayDoiTaiSan();
            dataRow[2] = nvtdts.getTenNhiemVu();
            dataRow[3] = nvtdts.getChiTietNhiemVu();
            dataRow[4] = nvtdts.getTienDo();
            nvtdtsModel.addRow(dataRow);
        }
    }
    
    public void resetForm(){
        jTextFieldID.setText("");
        jTextFieldIDKeHoachThayDoiTaiSan.setText(""); 
        jTextFieldTenNhiemVu.setText(""); 
        jTextFieldChiTietNhiemVu.setText("");
        jTextFieldTienDo.setText("");
    }
    
    public NhiemVuThayDoiTaiSan getModel(){
        NhiemVuThayDoiTaiSan nvtdts = new NhiemVuThayDoiTaiSan();
        nvtdts.setiD(jTextFieldID.getText().trim());
        nvtdts.setiDKeHoachThayDoiTaiSan(jTextFieldIDKeHoachThayDoiTaiSan.getText().trim());
        nvtdts.setTenNhiemVu(jTextFieldTenNhiemVu.getText().trim());
        nvtdts.setChiTietNhiemVu(jTextFieldChiTietNhiemVu.getText().trim());
        nvtdts.setTienDo(jTextFieldTienDo.getText().trim());
        return nvtdts;
    }
    
    NhiemVuThayDoiTaiSanDAO nvtdtsDAO = new NhiemVuThayDoiTaiSanDAO();
    
    public void setModel(NhiemVuThayDoiTaiSan nvtdts){
        jTextFieldID.setText(nvtdts.getiD());
        jTextFieldIDKeHoachThayDoiTaiSan.setText(nvtdts.getiDKeHoachThayDoiTaiSan());
        jTextFieldTenNhiemVu.setText(nvtdts.getTenNhiemVu());
        jTextFieldChiTietNhiemVu.setText(nvtdts.getChiTietNhiemVu());
        jTextFieldTienDo.setText(nvtdts.getTienDo());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldIDKeHoachThayDoiTaiSan = new javax.swing.JTextField();
        jTextFieldTenNhiemVu = new javax.swing.JTextField();
        jTextFieldChiTietNhiemVu = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNhiemVuThayDoiTaiSan = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldTienDo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("NHIỆM VỤ THAY ĐỔI TÀI SẢN");

        jLabel2.setText("ID");

        jLabel3.setText("ID kế hoạch thay đổi tài sản");

        jLabel4.setText("Tên nhiệm vụ");

        jLabel5.setText("Chi tiết nhiệm vụ");

        jButton1.setText("Tìm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Thêm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Sửa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Xóa");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Làm mới");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTableNhiemVuThayDoiTaiSan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "ID kế hoạch thay đổi tài sản", "Tên nhiệm vụ", "Chi tiết nhiệm vụ", "Tiến độ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableNhiemVuThayDoiTaiSan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableNhiemVuThayDoiTaiSanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableNhiemVuThayDoiTaiSan);

        jLabel6.setText("Tiến độ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldID)
                    .addComponent(jTextFieldChiTietNhiemVu, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                    .addComponent(jTextFieldTenNhiemVu)
                    .addComponent(jTextFieldIDKeHoachThayDoiTaiSan)
                    .addComponent(jTextFieldTienDo))
                .addGap(141, 141, 141)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldIDKeHoachThayDoiTaiSan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldTenNhiemVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldChiTietNhiemVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldTienDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTextFieldID.setEnabled(false);
        if(jTextFieldID.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập mã");
        } else {
            NhiemVuThayDoiTaiSan nvtdts = nvtdtsDAO.findNVTDTSByID(jTextFieldID.getText());
            if(nvtdts != null)
                setModel(nvtdts);
            else
                JOptionPane.showMessageDialog(this, "Không tìm thấy nhiệm vụ!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextFieldID.setEnabled(false);
        NhiemVuThayDoiTaiSan nvtdts = getModel();
        if(nvtdtsDAO.add(nvtdts) > 0){
            JOptionPane.showMessageDialog(this, "Thêm thành công!");
            fillTable();
        }
            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        NhiemVuThayDoiTaiSan nvtdts = getModel();
        jTextFieldID.setEnabled(false);
        if(nvtdtsDAO.update(nvtdts) > 0){
            JOptionPane.showMessageDialog(this, "Sửa thành công!");
            fillTable();
        }         
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(jTextFieldID.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập mã");
        } else {
            int result = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa?", "Xác nhận", JOptionPane.YES_NO_CANCEL_OPTION);    
            if (result == JOptionPane.YES_OPTION) {
                if(nvtdtsDAO.delete(jTextFieldID.getText()) > 0) {
                    JOptionPane.showMessageDialog(this, "Xóa thành công!");
                    fillTable();
                } else {
                    JOptionPane.showMessageDialog(this, "Không tìm thấy nhiệm vụ!");
                }
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        resetForm();
        jTextFieldID.setEnabled(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    String idClick = "-1";
    private void jTableNhiemVuThayDoiTaiSanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableNhiemVuThayDoiTaiSanMouseClicked
        // TODO add your handling code here:
        jTextFieldID.setEnabled(false);
        int position = jTableNhiemVuThayDoiTaiSan.rowAtPoint(evt.getPoint());
        idClick = jTableNhiemVuThayDoiTaiSan.getValueAt(position, 0).toString();
        NhiemVuThayDoiTaiSan nvtdts = nvtdtsDAO.findNVTDTSByID(idClick);
        if(nvtdts != null)
            setModel(nvtdts);
    }//GEN-LAST:event_jTableNhiemVuThayDoiTaiSanMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFNhiemVuThayDoiTaiSan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFNhiemVuThayDoiTaiSan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFNhiemVuThayDoiTaiSan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFNhiemVuThayDoiTaiSan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JFNhiemVuThayDoiTaiSan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNhiemVuThayDoiTaiSan;
    private javax.swing.JTextField jTextFieldChiTietNhiemVu;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldIDKeHoachThayDoiTaiSan;
    private javax.swing.JTextField jTextFieldTenNhiemVu;
    private javax.swing.JTextField jTextFieldTienDo;
    // End of variables declaration//GEN-END:variables
}
