/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import static java.lang.Integer.parseInt;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Models.TaiSanThayDoi;
import Models.TaiSanThayDoiDAO;

/**
 *
 * @author IT SUP
 */
public class JFTaiSanThayDoi extends javax.swing.JFrame {

    /**
     * Creates new form TaiSanThayDoi
     */
    public JFTaiSanThayDoi() {
        initComponents();
        fillTable();
    }

    public void updateTable() {
        DefaultTableModel tSModel = (DefaultTableModel) jTableTaiSanThayDoi.getModel();
        tSModel.setRowCount(0);
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        for (TaiSanThayDoi tstd : tstdDAO.getAll()) {
            Object dataRow[] = new Object[5];
            dataRow[0] = tstd.getMaTaiSan();
            dataRow[1] = tstd.getiDTaiSanPhongMay();
            dataRow[2] = tstd.getiDKeHoachThayDoiTaiSan();
            dataRow[3] = tstd.getSoLuong();
            dataRow[4] = tstd.getTrangThai();
            tSModel.addRow(dataRow);
        }
    }
    
    public void fillTable(){
        updateTable();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldMaTaiSan = new javax.swing.JTextField();
        jTextFieldIDTaiSanPhongMay = new javax.swing.JTextField();
        jTextFieldIDKeHoachThayDoiTaiSan = new javax.swing.JTextField();
        jTextFieldSoLuong = new javax.swing.JTextField();
        jTextFieldTrangThai = new javax.swing.JTextField();
        jButtonTim = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButtonThem = new javax.swing.JButton();
        jButtonSua = new javax.swing.JButton();
        jButtonXoa = new javax.swing.JButton();
        jButtonLamMoi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTaiSanThayDoi = new javax.swing.JTable();
        jButtonThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        jLabel1.setText("Mã tài sản");

        jLabel2.setText("ID tài sản phòng máy");

        jLabel3.setText("ID kế hoạch thay đổi tài sản");

        jLabel4.setText("Số lượng");

        jLabel5.setText("Trạng thái");

        jButtonTim.setText("Tìm");
        jButtonTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("TÀI SẢN THAY ĐỔI");

        jButtonThem.setText("Thêm");
        jButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemActionPerformed(evt);
            }
        });

        jButtonSua.setText("Sửa");
        jButtonSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaActionPerformed(evt);
            }
        });

        jButtonXoa.setText("Xóa");
        jButtonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaActionPerformed(evt);
            }
        });

        jButtonLamMoi.setText("Làm mới");
        jButtonLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLamMoiActionPerformed(evt);
            }
        });

        jTableTaiSanThayDoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã tài sản", "ID tài sản phòng máy", "ID kế hoạch thay đổi tài sản", "Số lượng", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableTaiSanThayDoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTaiSanThayDoiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTaiSanThayDoi);

        jButtonThoat.setText("Thoát");
        jButtonThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldMaTaiSan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldIDTaiSanPhongMay, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldIDKeHoachThayDoiTaiSan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldSoLuong, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldTrangThai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonThoat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldMaTaiSan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldIDTaiSanPhongMay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonThem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldIDKeHoachThayDoiTaiSan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonXoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLamMoi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonThoat)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    private void jButtonTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimActionPerformed
        // TODO add your handling code here:
        jTextFieldMaTaiSan.setEnabled(false);
        if(jTextFieldMaTaiSan.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập mã tài sản");
        } else {
            TaiSanThayDoi tstd = tstdDAO.findTSByID(jTextFieldMaTaiSan.getText());
            if(tstd != null)
                setModel(tstd);
            else
                JOptionPane.showMessageDialog(this, "Không tìm thấy tài sản");
        }
    }//GEN-LAST:event_jButtonTimActionPerformed

    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed
        // TODO add your handling code here:
        TaiSanThayDoi tstd = getModel();
        if(tstdDAO.add(tstd) > 0){
            JOptionPane.showMessageDialog(this, "Thêm thành công!");
            updateTable();
        }
    }//GEN-LAST:event_jButtonThemActionPerformed

    private void jButtonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaActionPerformed
        // TODO add your handling code here:
        TaiSanThayDoi tstd = getModel();
        jTextFieldMaTaiSan.setEnabled(false);
        if(tstdDAO.update(tstd) > 0)
        {
            JOptionPane.showMessageDialog(this, "Sửa thành công!");
            updateTable();
        }  
    }//GEN-LAST:event_jButtonSuaActionPerformed

    private void jButtonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaActionPerformed
        // TODO add your handling code here:
        if(jTextFieldMaTaiSan.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập mã tài sản");
        } else {
            int result = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn sửa?", "Xác nhận", JOptionPane.YES_NO_CANCEL_OPTION);    
            if (result == JOptionPane.YES_OPTION) {
                if(tstdDAO.delete(jTextFieldMaTaiSan.getText()) > 0) {
                    JOptionPane.showMessageDialog(this, "Xóa thành công!");
                    updateTable();
                } else {
                    JOptionPane.showMessageDialog(this, "Không tìm thấy tài sản!");
                }
            }
        }
    }//GEN-LAST:event_jButtonXoaActionPerformed

    String maTaiSanThayDoiClick = "-1";
    private void jTableTaiSanThayDoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTaiSanThayDoiMouseClicked
        // TODO add your handling code here:
        jTextFieldMaTaiSan.setEnabled(false);
        int position = jTableTaiSanThayDoi.rowAtPoint(evt.getPoint());
        maTaiSanThayDoiClick = jTableTaiSanThayDoi.getValueAt(position, 0).toString();
        TaiSanThayDoi tstd = tstdDAO.findTSByID(maTaiSanThayDoiClick);
        if(tstd != null)
            setModel(tstd);
    }//GEN-LAST:event_jTableTaiSanThayDoiMouseClicked

    private void jButtonLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLamMoiActionPerformed
        // TODO add your handling code here:
        resetForm();
        jTextFieldMaTaiSan.setEnabled(true);
    }//GEN-LAST:event_jButtonLamMoiActionPerformed

    private void jButtonThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThoatActionPerformed
        // TODO add your handling code here:
        SubMenuQuanLyThayDoiTaiSan smqltdts = new SubMenuQuanLyThayDoiTaiSan();
        smqltdts.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonThoatActionPerformed
    
    public void resetForm(){
        jTextFieldMaTaiSan.setText("");
        jTextFieldIDTaiSanPhongMay.setText("");
        jTextFieldIDKeHoachThayDoiTaiSan.setText("");
        jTextFieldSoLuong.setText("");
        jTextFieldTrangThai.setText("");       
    }
    
    TaiSanThayDoiDAO tstdDAO = new TaiSanThayDoiDAO();
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFTaiSanThayDoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFTaiSanThayDoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFTaiSanThayDoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFTaiSanThayDoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JFTaiSanThayDoi().setVisible(true);
            }
        });
    }

    public TaiSanThayDoi getModel(){
        TaiSanThayDoi tstd = new TaiSanThayDoi();
        tstd.setMaTaiSan(jTextFieldMaTaiSan.getText().trim());
        tstd.setiDTaiSanPhongMay(jTextFieldIDTaiSanPhongMay.getText().trim());   
        tstd.setiDKeHoachThayDoiTaiSan(jTextFieldIDKeHoachThayDoiTaiSan.getText().trim());
        tstd.setSoLuong(parseInt(jTextFieldSoLuong.getText().trim()));
        tstd.setTrangThai(jTextFieldTrangThai.getText().trim());
        return tstd;
    }
    
    public void setModel(TaiSanThayDoi tstd){     
        jTextFieldMaTaiSan.setText(tstd.getMaTaiSan());
        jTextFieldIDTaiSanPhongMay.setText(tstd.getiDTaiSanPhongMay());
        jTextFieldIDKeHoachThayDoiTaiSan.setText(tstd.getiDKeHoachThayDoiTaiSan());            
        jTextFieldSoLuong.setText(Integer.toString(tstd.getSoLuong()));
        jTextFieldTrangThai.setText(tstd.getTrangThai());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLamMoi;
    private javax.swing.JButton jButtonSua;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonThoat;
    private javax.swing.JButton jButtonTim;
    private javax.swing.JButton jButtonXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTaiSanThayDoi;
    private javax.swing.JTextField jTextFieldIDKeHoachThayDoiTaiSan;
    private javax.swing.JTextField jTextFieldIDTaiSanPhongMay;
    private javax.swing.JTextField jTextFieldMaTaiSan;
    private javax.swing.JTextField jTextFieldSoLuong;
    private javax.swing.JTextField jTextFieldTrangThai;
    // End of variables declaration//GEN-END:variables
}
