/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controllers.KeHoachBaoTriController;
import Interfaces.ErrorNormal;
import Models.KeHoachBaoTri;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author thinh
 */
public class XacNhanThucThiView extends javax.swing.JFrame {

    private File selectedFile;
    private BufferedImage selectedImage;
    private KeHoachBaoTriController keHoachBaoTriController;
    private KeHoachBaoTri keHoachBaoTri;
    
    
    public XacNhanThucThiView() {
        initComponents();
    }
    
    public XacNhanThucThiView(KeHoachBaoTriController keHoachBaoTriController, KeHoachBaoTri keHoachBaoTri) {
        initComponents();
        this.keHoachBaoTriController = keHoachBaoTriController;
        this.keHoachBaoTri = keHoachBaoTri;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FileChooserContainer = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        Btn_cancel = new javax.swing.JButton();
        Btn_confirm = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Btn_addImg = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ImageContainer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Xác nhận thực thi");

        Btn_cancel.setText("Hủy");

        Btn_confirm.setText("Xác nhận");
        Btn_confirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_confirmMouseClicked(evt);
            }
        });

        jLabel2.setText("Hãy thêm ảnh xác nhận để bắt đàu thực thi kế hoạch");

        Btn_addImg.setText("Chọn ảnh");
        Btn_addImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_addImgMouseClicked(evt);
            }
        });

        jLabel3.setText("Ảnh đã chọn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(Btn_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(203, 203, 203)
                        .addComponent(Btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102)
                                .addComponent(ImageContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(382, 382, 382)
                        .addComponent(Btn_addImg)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(252, 252, 252))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_addImg))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(ImageContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_addImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_addImgMouseClicked
        int result = FileChooserContainer.showOpenDialog(this);
        if (result == FileChooserContainer.APPROVE_OPTION) {
            selectedFile = FileChooserContainer.getSelectedFile();
            try {
                selectedImage = ImageIO.read(selectedFile);
                
                int labelWidth = ImageContainer.getWidth();
                int labelHeight = ImageContainer.getHeight();
                Image scaledImage = selectedImage.getScaledInstance(labelWidth, labelHeight, Image.SCALE_SMOOTH);
                ImageIcon iconForDisplay = new ImageIcon(scaledImage);
                ImageContainer.setIcon(iconForDisplay);
            } catch (IOException ex) {
                ErrorNormal errorNormal = new ErrorNormal(ex.getMessage());
                errorNormal.HienThiThongBaoLoi();
            }
        }
    }//GEN-LAST:event_Btn_addImgMouseClicked

    private void Btn_confirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_confirmMouseClicked
        try {
            if(!luuTruFile()) {
                return;
            }
            if(keHoachBaoTriController.xacNhanThucThiKeHoach(keHoachBaoTri) == 1) {
                this.dispose();
                keHoachBaoTriController.getChiTietKeHoachBaoTriView().dispose();
                keHoachBaoTriController.navigateQuanLyBaoTriViewAndUpdateKeHoachBaotriTable_ThucThiBaoTriTable();
            }
        } catch (IOException ex) {
            ErrorNormal errorNormal = new ErrorNormal(ex.getMessage());
            errorNormal.HienThiThongBaoLoi();
        }
    }//GEN-LAST:event_Btn_confirmMouseClicked

    private boolean luuTruFile() throws IOException {
        String extension = "";
        
        if(selectedFile != null) {
            String fileName = selectedFile.getName();
            int i = fileName.lastIndexOf('.');
            if (i > 0 && i < fileName.length() - 1) {
                extension = fileName.substring(i + 1).toLowerCase();
            }        
            File pathFolder = new File("src\\main\\java\\icons");
            File pathFile = new File(pathFolder.getAbsolutePath() + "\\" + fileName);

            ImageIO.write(selectedImage, extension, pathFile);
            keHoachBaoTri.setAnhXacNhan(fileName);
            return true;
        } else {
            ErrorNormal errorNormal = new ErrorNormal("Bạn chưa chọn ảnh");
            errorNormal.HienThiThongBaoLoi();
        }
        return false;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XacNhanThucThiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XacNhanThucThiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XacNhanThucThiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XacNhanThucThiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XacNhanThucThiView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_addImg;
    private javax.swing.JButton Btn_cancel;
    private javax.swing.JButton Btn_confirm;
    private javax.swing.JFileChooser FileChooserContainer;
    private javax.swing.JLabel ImageContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
